"""rename_product_id_to_machine_id

Revision ID: 71841d7fe831
Revises: '66ac22c63174'
Create Date: 2026-07-21 21:51:10.171540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71841d7fe831'
down_revision: Union[str, None] = '66ac22c63174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry_logs', sa.Column('machine_id', sa.String(length=50), nullable=True))
    op.execute("UPDATE telemetry_logs SET machine_id = product_id")
    op.alter_column('telemetry_logs', 'machine_id', nullable=False)
    op.alter_column('telemetry_logs', 'product_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(op.f('telemetry_logs_product_id_fkey'), 'telemetry_logs', type_='foreignkey')
    op.create_foreign_key(None, 'telemetry_logs', 'machines', ['machine_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telemetry_logs', type_='foreignkey')
    op.create_foreign_key(op.f('telemetry_logs_product_id_fkey'), 'telemetry_logs', 'machines', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('telemetry_logs', 'product_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('telemetry_logs', 'machine_id')
    # ### end Alembic commands ###
